#!/bin/bash

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

main_menu_height=210px
main_menu_width=300px

apps_kbdn="󰀻  Apps Keybinds"
sys_kbdn="  System Keybinds"
quit="Exit 󰈆 "

select=$(echo -e "$sys_kbdn\n$apps_kbdn\n$quit" | rofi -x11 -dmenu -i -p '   Keybinds ' -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height;}" -theme $path_to_theme)

case $select in
$apps_kbdn)
	~/.config/hypr/rofi_hyprland/rofi-hyprland-keybinds/rofi-hypr-keybinds-apps.sh
	;;
$sys_kbdn)
	~/.config/hypr/rofi_hyprland/rofi-hyprland-keybinds/rofi-hypr-keybinds-system.sh
	;;
esac
