#!/bin/bash
### POLYBAR SUBMENU

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

#when add new entry make sure to add 35 to height
waybar_submenu_height=245px
waybar_submenu_width=280px

waybar_style_submenu_height=320px
waybar_style_submenu_width=480px
waybar_config_submenu_height=215px
waybar_config_submenu_width=280px

waybar_submenu() {

	waybar_main_cfg_sub="  Config  "
	waybar_color_sub="  Colors  "
	bar_start="󱓞  Bar Startup"

	#when add new entry make sure to add 35 to height
	waybar_select=$(echo -e "$waybar_main_cfg_sub\n$waybar_color_sub\n$bar_start\n$goback" | rofi -x11 -dmenu -i -theme-str "window {height: $waybar_submenu_height; width: $waybar_submenu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Waybar   " -theme $path_to_theme)

	case $waybar_select in
	$waybar_main_cfg_sub)
		waybar_config_submenu
		;;
	$waybar_color_sub)
		waybar_style_submenu
		;;
	$bar_start)
		$TERMINAL -e nvim ~/.config/waybar/startup.sh
		;;
	$goback)
		main_menu
		;;
	esac
}

waybar_config_submenu() {

	waybar_cfg_top="  Bar Top "
	waybar_cfg_bottom="  Bar Bottom "

	#when add new entry make sure to add 35 to height
	select_config=$(echo -e "$waybar_cfg_bottom\n$waybar_cfg_top\n$goback" | rofi -x11 -dmenu -i -theme-str "window {height: $waybar_config_submenu_height; width: $waybar_config_submenu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Polybar   " -theme $path_to_theme)

	case $select_config in
	$waybar_cfg_bottom)
		$TERMINAL -e nvim ~/.config/waybar/bar_config/bottom_bar.jsonc
		;;
	$waybar_cfg_top)
		$TERMINAL -e nvim ~/.config/waybar/bar_config/top_bar.jsonc
		;;
	$goback)
		waybar_submenu
		;;
	esac
}

waybar_style_submenu() {

	waybar_color_dark="  Dark Theme "
	waybar_color_white="  White Theme "
	waybar_color_expressive="  Expressive Theme"
	waybar_color_expressive_dynamic="  Expressive Theme (Dynamic)"
	waybar_color_expressive_dynamic_rounded="  Expressive Theme (Dynamic, Rounded)"

	#when add new entry make sure to add 35 to height
	select_style=$(echo -e "$waybar_color_dark\n$waybar_color_white\n$waybar_color_expressive\n$waybar_color_expressive_dynamic\n$waybar_color_expressive_dynamic_rounded\n$goback" | rofi -x11 -dmenu -i -theme-str "window {height: $waybar_style_submenu_height; width: $waybar_style_submenu_width;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Polybar   " -theme $path_to_theme)

	case $select_style in
	$waybar_color_white)
		$TERMINAL -e nvim ~/.config/waybar/bar_style/white.css
		;;
	$waybar_color_dark)
		$TERMINAL -e nvim ~/.config/waybar/bar_style/dark.css
		;;
	$waybar_color_expressive)
		$TERMINAL -e nvim ~/.config/waybar/bar_style/expressive.css
		;;
	$waybar_color_expressive_dynamic)
		$TERMINAL -e nvim ~/.config/waybar/bar_style/dynamic.css
		;;
	$waybar_color_expressive_dynamic_rounded)
		$TERMINAL -e nvim ~/.config/waybar/bar_style/dynamic_round.css
		;;
	$goback)
		waybar_submenu
		;;
	esac
}
