#!/usr/bin/env bash

#COULD NOT FIND THE ORIGINAL AUTHOR
#THIS SCRIPT WAS MODIFIED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config

main_menu_height=470px
main_menu_width=340px

bar_top=${bar_top:-false}
rofi_theme=${rofi_theme:-black}
use_hyprshutdown=${use_hyprshutdown:-false}

if [[ $bar_top == "true" ]]; then
	location="north east"

	main_menu_x_offset=-10px
	main_menu_y_offset=70px
else
	location="south east"

	main_menu_x_offset=-10px
	main_menu_y_offset=-70px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

# uptime and hosts
uptime=$(uptime -p | sed -e 's/up //g' | awk -F'[ ,]+' '{d=h=m=0; for(i=1;i<=NF;i++){if($i=="day"||$i=="days")d=$(i-1); if($i=="hour"||$i=="hours")h=$(i-1); if($i=="minute"||$i=="minutes")m=$(i-1);} out=""; if(d>0)out=out d "d, "; if(h>0)out=out h "h, "; if(m>0)out=out m "m"; sub(/, $/,"",out); print out}')
if [[ $uptime == "" ]]; then
	uptime="Just Now"
fi
user=$(whoami)
host=$(hostname)

# Options
shutdown='  Power off'
reboot='  Reboot'
reboot_firmware='  Reboot to UEFI/BIOS'
lock='  Lock'
suspend='󰤄  Suspend'
logout='󰍃  Log out'
screensaver="󰷜  Screensaver"

if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
	choice_list="$lock\n$screensaver\n$suspend\n$logout\n$reboot_firmware\n$reboot\n$shutdown"
else
	choice_list="$lock\n$suspend\n$logout\n$reboot_firmware\n$reboot\n$shutdown"
fi

chosen=$(echo -e "$choice_list" | rofi -x11 -dmenu -i -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme -p " Power Menu   " -mesg "$(echo -e "󰥔  Uptime: $uptime\n  Host: $host\n  User: $user")")

case $chosen in
$shutdown)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		systemctl --user stop hyprpolkitagent
	fi
	poweroff
	;;
$reboot_firmware)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		systemctl --user stop hyprpolkitagent
	fi
	systemctl reboot --firmware-setup
	;;
$reboot)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		systemctl --user stop hyprpolkitagent
	fi
	reboot
	;;
$lock)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		bash -c '! pidof -x hyprlock_current_bg.sh > /dev/null && ~/.config/hypr/scripts/hyprlock_current_bg.sh'
	else
		betterlockscreen -l
	fi
	;;
$suspend)
	systemctl suspend
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		bash -c '! pidof -x hyprlock_current_bg.sh > /dev/null && ~/.config/hypr/scripts/hyprlock_current_bg.sh'
	else
		betterlockscreen -l
	fi
	;;
$logout)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		if [[ $use_hyprshutdown == "false" ]]; then
			# Gracefully stop the Portals (This is what usually hangs Flatpaks)
			# Kill the Hyprland and GTK implementations first, then the main portal
			pkill -TERM -f "xdg-desktop-portal-hyprland|xdg-desktop-portal-gtk"
			pkill -TERM -x "xdg-desktop-portal"

			# Kill all Flatpak app processes
			# This looks for processes running inside the flatpak sandbox
			if command -v flatpak &>/dev/null; then
				# We target the 'bwrap' (bubblewrap) processes that Flatpak uses
				pkill -TERM -u "$USER" -f "bwrap"
			fi

			# Kill browsers and VPNs
			pkill -SIGTERM -f "chrome|firefox|brave|zen-browser|librewolf|protonvpn|mullvad"

			# Cleanup UI and custom scripts
			systemctl --user stop hyprpolkitagent
			killall -SIGINT waybar
			killall swaybg mpvpaper dunst hypridle pactl udevadm activate-linux easyeffects 2>/dev/null

			# Exit
			sleep 0.5
			# hyprctl dispatch exit
			hyprctl dispatch 'hl.dsp.exit()'
			pkill -u "$USER" -f "\.sh"

			exit 0
		else
			hyprshutdown
		fi

	elif [[ $XDG_CURRENT_DESKTOP == "sway" ]]; then
		waydroid session stop
		swaymsg exit
	else
		killall dunst
		i3-msg 'exit'
	fi
	;;
$screensaver)
	~/.config/hypr/scripts/hyprland_screensaver.sh
	;;
esac
