#!/usr/bin/bash

#THIS SCRIPT WAS FABRICATED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config

main_menu_height=360px
main_menu_width=540px
manual_menu_height=90px
manual_menu_width=480px

bar_top=${bar_top:-false}
rofi_theme=${rofi_theme:-black}

if [[ $bar_top == "true" ]]; then
	location="north east"

	main_menu_x_offset=-10px
	main_menu_y_offset=70px

	playback_menu_x_offset=-10px
	playback_menu_y_offset=70px

	ouputdev_menu_x_offset=-10px
	ouputdev_menu_y_offset=70px

	inputdev_menu_x_offset=-10px
	inputdev_menu_y_offset=70px

	devconfig_menu_x_offset=-10px
	devconfig_menu_y_offset=70px

	manual_menu_x_offset=-20px
	manual_menu_y_offset=70px

else
	location="south east"

	main_menu_x_offset=-10px
	main_menu_y_offset=-70px

	playback_menu_x_offset=-10px
	playback_menu_y_offset=-70px

	ouputdev_menu_x_offset=-10px
	ouputdev_menu_y_offset=-70px

	inputdev_menu_x_offset=-10px
	inputdev_menu_y_offset=-70px

	devconfig_menu_x_offset=-10px
	devconfig_menu_y_offset=-70px

	manual_menu_x_offset=-20px
	manual_menu_y_offset=-70px

fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
	path_to_theme_set="~/.config/rofi/rofi_theme/white/white-set.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
	path_to_theme_set="~/.config/rofi/rofi_theme/black/black-set.rasi"
fi

#main

goback="Back 󰌍 "
quit="Exit 󰈆 "

outputdev_opt="󰜟  Outpur Device  "
inputdev_opt="󱦉  Input Device  "
devconfig_opt="  Device Configuration  "
manual_volume_opt="   Set Volume Level  "
desktop_audio_player="󰖯  Toggle Desktop Audio Player (QuickShell)"
pavucontrol_opt="󰖯  Pulseaudio Control GUI"

opt_list="$manual_volume_opt\n$outputdev_opt\n$inputdev_opt\n$devconfig_opt\n$desktop_audio_player\n$pavucontrol_opt\n$quit"

ouput_dev_card=$(pactl list cards | grep "device.name" | sed 's/device.name =//g' | sed 's/"//g' | sed 's/\t//g' | sed 's/ //g')
current_output_dev=$(pactl list sinks short | grep RUNNING | awk '{print $2}' | sed 's/bluez_output.//g' | sed 's/\..*//')

main_menu() {
	select=$(echo -e "$opt_list" | rofi -x11 -dmenu -i -theme-str "window {height: $main_menu_height; width: $main_menu_width; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme-str "listview {columns: 1; layout: vertical;}" -p " Audio   " -theme $path_to_theme)

	case $select in
	$playback_opt)
		playback_func
		;;
	$outputdev_opt)
		outputdev_func
		;;
	$inputdev_opt)
		inputdev_func
		;;
	$devconfig_opt)
		devconfig_func
		;;
	$manual_volume_opt)
		manual_set_volume_func
		;;
	$pavucontrol_opt)
		pavucontrol
		;;
	$desktop_audio_player)
		audio_player_qs_launch_func
		;;
	esac
}

manual_set_volume_func() {
	input_vol_percent=$(rofi -x11 -dmenu -i -p " Volume   (From 0 -> 153) " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {height: $manual_menu_height; width: $manual_menu_width; location: $location; x-offset: $manual_menu_x_offset; y-offset: $manual_menu_y_offset;}" -theme $path_to_theme_set)
	case $input_vol_percent in
	"")
		exit 0
		;;
	esac
	if [[ $input_vol_percent -lt 0 ]] || [[ $input_vol_percent -gt 153 ]]; then
		main_menu
	else
		pactl set-sink-volume @DEFAULT_SINK@ $input_vol_percent%
		$volume_script volume_status
		main_menu
	fi
}

outputdev_func() {
	outputdev_list=$(pactl list | grep node.name | grep -E "(alsa_output|bluez_output)" | sed 's/"//g' | sed 's/node.name = //g' | uniq -u | sed 's/alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.//g' | sed 's/bluez_output.//g' | sed 's/\t//g' | sort | uniq)

	outputdev_menu_height=140
	numbers_of_outputdev=$(echo "$outputdev_list" | wc -l)
	height_per_outputdev=$((outputdev_menu_height + (numbers_of_outputdev * 38)))
	if [[ $height_per_outputdev -gt 710 ]]; then
		height_per_outputdev=710
	fi

	select_output=$(echo -e "$outputdev_list\n$goback" | rofi -x11 -dmenu -i -theme-str "listview {columns: 1; layout: vertical;}" -p " Output 󰜟  " -theme-str "window {location: $location; x-offset: $ouputdev_menu_x_offset; y-offset: $ouputdev_menu_y_offset; height: ${height_per_outputdev};}" -theme $path_to_theme)
	if [[ $select_output == $goback ]]; then
		main_menu
	else
		first_try=$(pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.$select_output)
		echo $first_try
		if [[ $first_try == "" ]]; then
			second_try=$(pactl set-default-sink bluez_output.$select_output)
		fi
	fi
}

inputdev_func() {
	inputdev_list=$(pactl list | grep node.name | grep -E "(alsa_input|bluez_input)" | sed 's/"//g' | sed 's/node.name = //g' | uniq -u | sed 's/alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.//g' | sed 's/bluez_input.//g' | sed 's/\t//g' | sort | uniq)

	inputdev_menu_height=140
	numbers_of_inputdev=$(echo "$inputdev_list" | wc -l)
	height_per_inputdev=$((inputdev_menu_height + (numbers_of_inputdev * 38)))
	if [[ $height_per_inputdev -gt 710 ]]; then
		height_per_inputdev=710
	fi

	select_input=$(echo -e "$inputdev_list\n$goback" | rofi -x11 -dmenu -i -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {location: $location; x-offset: $inputdev_menu_x_offset; y-offset: $inputdev_menu_y_offset; height: ${height_per_inputdev};}" -p " Input 󱦉  " -theme $path_to_theme)
	if [[ $select_input == $goback ]]; then
		main_menu
	else
		first_try=$(pactl set-default-source alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.$select_input)
		echo $first_try
		if [[ $first_try == "" ]]; then
			second_try=$(pactl set-default-source bluez_input.$select_input)
		fi
	fi
}

devconfig_func() {
	devconfig_list=$(pactl list cards | grep -A 15 "Profiles" | sed -n '/Profiles:/,/Active Profile:/p' | grep -E "(Profile:|Active Profile:|available:)" | sed -E 's/^[ \t]*//; s/\(available: .*\)//' | sed 's/Profile: //' | grep -v "Active" | awk -F':' '{print $1}')

	devconfig_menu_height=140
	numbers_of_configs=$(echo "$devconfig_list" | wc -l)
	height_per_configs=$((devconfig_menu_height + (numbers_of_configs * 38)))
	if [[ $height_per_configs -gt 710 ]]; then
		height_per_configs=710
	fi

	select_profile=$(echo -e "$devconfig_list\n$goback" | rofi -x11 -dmenu -i -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {location: $location; x-offset: $devconfig_menu_x_offset; y-offset: $devconfig_menu_y_offset; height: ${height_per_configs};}" -p " Configuration   " -theme $path_to_theme)
	if [[ $select_profile == $goback ]]; then
		main_menu
	fi
	first_try=$(pactl set-card-profile alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic "$select_profile")
	if [[ $first_try == "" ]]; then
		second_try=$(pactl set-card-profile bluez_card.$current_output_dev "$select_profile")
	fi
}

audio_player_qs_launch_func() {
	local qs_state_file="/tmp/qs_state"
	local state

	if ! command -v qs &>/dev/null; then
		notify-send "Error!" "\"qs\" binary not found!"
		paplay $CUSTOM_SOUND_PATH/battery-low.oga
		main_menu
	else
		state=$(cat "$qs_state_file" 2>/dev/null || echo 0)

		if [[ "$state" == "0" ]]; then
			qs &
			echo 1 >"$qs_state_file"
			notify-send "Music Player: On"
			main_menu
		else
			killall qs
			echo 0 >"$qs_state_file"
			notify-send "Music Player: Off"
			main_menu
		fi
	fi

}

main_menu
