#!/usr/bin/env bash

#when add new entry make sure to add 35 to height
main_menu_height=265px
main_menu_width=375px

value_menu_height=90px
value_menu_width=600px

source ~/.config/dtf-config/config

bar_top=${bar_top:-false}
rofi_theme=${rofi_theme:-black}

if [[ $bar_top == "true" ]]; then
	location="north west"

	main_menu_x_offset=10px
	main_menu_y_offset=70px
else
	location="south west"

	main_menu_x_offset=10px
	main_menu_y_offset=-70px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white-set.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black-set.rasi"
fi

start="  Start (Default: 4800)"
start_custom="󱤵  Start Custom"
reset="  Reset"
quit="Exit 󰈆 "

start_custom_func() {
	percentage=$(rofi -dmenu -theme $path_to_theme -i -p " Set Custom   (From 4500 -> 6500) " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $value_menu_width; height: $value_menu_height; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}")
	case $percentage in
	"")
		exit 0
		;;
	esac
	if [[ $percentage -lt 4500 ]] || [[ $percentage -gt 6500 ]]; then
		main
	else
		redshift -PO $percentage
		main
	fi
}

main() {
	select=$(echo -e "$start\n$start_custom\n$reset\n$quit" | rofi -dmenu -theme $path_to_theme -i -p " Night Mode   " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}")

	case $select in
	$start)
		redshift -PO 4800
		main
		;;
	$start_custom)
		start_custom_func
		;;
	$reset)
		redshift -x
		main
		;;
	$quit)
		exit 0
		;;
	esac
}

main
