#!/bin/bash

source ~/.config/dtf-config/config
bar_top=${bar_top:-false}
rofi_theme=${rofi_theme:-black}

if [[ $LAUNCHED_FROM_BAR == "true" ]]; then
	if [[ $bar_top == "true" ]]; then
		location="north west"

		main_menu_x_offset=10px
		main_menu_y_offset=70px
	else
		location="south west"

		main_menu_x_offset=10px
		main_menu_y_offset=-70px
	fi
else
	location="center"
	main_menu_x_offset=0px
	main_menu_y_offset=0px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
fi

main_menu_height=510px
main_menu_width=390px

wm_settings="󰢹  Desktop Settings "
wm_reload="󰑓  Desktop Reload"
usr_settings="  User Settings"
hyprland_custom_settings="  Hyprland Custom Settings"
monitor_settings="󱒃  Monitor Settings "
power_mode_settings="󰓅  Power Mode Settings "
default_browser="󰖟  Default Web Browser "
default_file_manager="  Default File Manger "
system_update_upgrade="󰚰  Full System Upgrade"
system_information="  System Info "
quit="Exit 󰈆 "

select=$(echo -e "$wm_settings\n$wm_reload\n$usr_settings\n$hyprland_custom_settings\n$system_update_upgrade\n$monitor_settings\n$power_mode_settings\n$default_browser\n$default_file_manager\n$system_information\n$quit" | rofi -x11 -dmenu -i -p ' Settings   ' -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme)

case $select in
$wm_settings)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		~/.config/hypr/rofi_hyprland/hyprland_settings/rofi-hyprland-settings
	elif [[ $XDG_CURRENT_DESKTOP == "i3" ]]; then
		~/.config/i3/scripts/i3-settings/rofi-i3-settings
	fi
	;;
$wm_reload)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hyprctl reload
	elif [[ $XDG_CURRENT_DESKTOP == "i3" ]]; then
		i3-msg restart
	fi
	;;
$usr_settings)
	$TERMINAL -e nvim ~/.config/dtf-config/config &
	;;
$monitor_settings)
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		~/.config/rofi/modules/rofi-monitor-settings
	elif [[ $XDG_CURRENT_DESKTOP == "i3" ]]; then
		arandr
	fi
	;;
$power_mode_settings)
	LAUNCHED_FROM_SETTINGS=true ~/.config/rofi/modules/rofi-power-mode
	;;
$default_file_manager)
	~/.config/rofi/modules/rofi-default-file-manager
	;;
$default_browser)
	~/.config/rofi/modules/rofi-default-browser
	;;
$system_update_upgrade)
	$TERMINAL -e ~/.config/rofi/scripts/rofi_user_settings_system_upgrade.sh &
	;;
$system_information)
	~/.config/rofi/modules/rofi-os-about
	;;
$hyprland_custom_settings)
	$TERMINAL -e nvim ~/.config/hypr/custom/ &
	;;
esac
