#!/usr/bin/env bash

#ORIGINAL IDEAS WAS MADE BY THIS GUY, NOT ME
#link to the king: https://github.com/ericmurphyxyz/rofi-wifi-menu
#THIS SCRIPT WAS MODIFIED BY ME (Xgameisdabest, aka xytozine)

source ~/.config/dtf-config/config
rofi_theme=${rofi_theme:-black}
bar_top=${bar_top:-false}

main_menu_height=430px
main_menu_disabled_height=250px
main_menu_width=300px
main_menu_height_ethernet=345px
main_menu_width_ethernet=380px
main_menu_height_both_down=275px
main_menu_width_both_down=340px

if [[ $bar_top == "true" ]]; then
	location="north east"

	main_menu_x_offset=-235px
	main_menu_y_offset=70px

	saved_menu_x_offset=-10px
	saved_menu_y_offset=70px

	list_menu_x_offset=-10px
	list_menu_y_offset=70px

else
	location="south east"

	main_menu_x_offset=-235px
	main_menu_y_offset=-70px

	saved_menu_x_offset=-10px
	saved_menu_y_offset=-70px

	list_menu_x_offset=-10px
	list_menu_y_offset=-70px
fi

if [[ $rofi_theme == "white" ]]; then
	path_to_theme="~/.config/rofi/rofi_theme/white/white.rasi"
	path_to_theme_set="~/.config/rofi/rofi_theme/white/white-set.rasi"
	path_to_theme_search="~/.config/rofi/rofi_theme/white/white-search.rasi"
else
	path_to_theme="~/.config/rofi/rofi_theme/black/black.rasi"
	path_to_theme_set="~/.config/rofi/rofi_theme/black/black-set.rasi"
	path_to_theme_search="~/.config/rofi/rofi_theme/black/black-search.rasi"
fi

connected_symbol="󰓢󱚽 "
goback="Back 󰌍 "
goback_wifilist="Back 󰌍 (To Refresh)"
quit="Exit 󰈆 "

main_menu_wifi() {
	connected=$(nmcli -fields WIFI g)
	if [[ "$connected" =~ "enabled" ]]; then
		toggle="󱛅  Disable Wi-Fi"
	elif [[ "$connected" =~ "disabled" ]]; then
		toggle="󱚽  Enable Wi-Fi"
	fi

	connection_manager="󰖯  Network Manager"
	wifi_list_opt="  Wifi List  "
	saved_list_opt="  Saved Wifi  "
	hidden_network_connect="󰈉  Hidden Wifi (Manual)  "
	hotspot="  Hotspot"

	if [[ $toggle == "󱛅  Disable Wi-Fi" ]]; then
		select=$(echo -e "$wifi_list_opt\n$toggle\n$hotspot\n$hidden_network_connect\n$saved_list_opt\n$connection_manager\n$quit" | rofi -x11 -dmenu -i -p " Network 󱛃  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_height; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme -mesg "$display_msg")
	else
		select=$(echo -e "$toggle\n$saved_list_opt\n$connection_manager\n$quit" | rofi -x11 -dmenu -i -p " Network 󱛃  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width; height: $main_menu_disabled_height; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme)
	fi

	if [ "$select" = "󱚽  Enable Wi-Fi" ]; then
		nmcli radio all on
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Wifi Enabled 󱚽 " -t 850
		main_menu_wifi
	elif [ "$select" = "󱛅  Disable Wi-Fi" ]; then
		nmcli radio all off
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Wifi Disabled 󱛅 " -t 850
		main_menu_wifi
	fi

	case $select in
	$wifi_list_opt)
		wifi_list_fn
		;;
	$saved_list_opt)
		wifi_saved_fn
		;;
	$connection_manager)
		nm-connection-editor
		;;
	$hidden_network_connect)
		connect_hidden_network
		;;
	$hotspot)
		wihotspot-gui
		;;
	$quit | "")
		exit 0
		;;
	esac
}

wifi_saved_fn() {
	saved_list=$(nmcli -t -f ACTIVE,NAME,TYPE connection show | sed "s/yes:/$connected_symbol /g" | sed "s/no://g" | grep -i wireless | cut -d ":" -f1 | awk '{print $0 " "}')

	wifi_saved_menu_height=175
	numbers_of_saved_wifi=$(echo "$saved_list" | wc -l)
	height_per_saved_entry=$((wifi_saved_menu_height + (numbers_of_saved_wifi * 38)))
	if [[ $height_per_saved_entry -gt 710 ]]; then
		height_per_saved_entry=710
	fi

	chosen_saved_select=$(echo -e "$saved_list\n$goback\n$quit" | rofi -x11 -dmenu -i -p " Saved Wifi  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {location: $location; x-offset: $saved_menu_x_offset; y-offset: $saved_menu_y_offset; height: ${height_per_saved_entry}px;}" -theme $path_to_theme)
	if [[ $chosen_saved_select == $goback ]]; then
		main_menu_wifi
	elif [[ $chosen_saved_select == $quit || $chosen_saved_select == "" ]]; then
		exit 0
	else

		chosen_saved=$(echo "$chosen_saved_select" | sed "s/$connected_symbol //g" | sed "s/ //g")
		connect_saved_opt="󰌹  Connect"
		delete_saved_opt="󰗨  Remove"

		selected_saved=$(echo -e "$connect_saved_opt\n$delete_saved_opt\n$goback\n$quit" | rofi -x11 -dmenu -i -p " $chosen_saved  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {location: $location; x-offset: $saved_menu_x_offset; y-offset: $saved_menu_y_offset;}" -theme $path_to_theme)

		if [[ $selected_saved == $delete_saved_opt ]]; then
			echo $chosen_saved
			nmcli connection delete "$chosen_saved"
			notify-send "󰗨 Removing Network \"$chosen_saved\"..."
			sleep 2
			notify-send "󰗨 Removed Network \"$chosen_saved\""
			wifi_saved_fn
		elif [[ $selected_saved == $connect_saved_opt ]]; then
			attempt_message="Attempting to connect to \"$chosen_saved\""
			success_message="You are now connected to Wi-Fi network \"$chosen_saved\"!"
			notify-send "$attempt_message" && nmcli connection up id "$chosen_saved" | grep "successfully" && notify-send "Connection Established!" "$success_message"
		elif [[ $selected_saved == $goback ]]; then
			wifi_saved_fn
		elif [[ $selected_saved == $quit || $selected_saved == "" ]]; then
			exit 0
		fi
	fi
}

wifi_list_fn() {
	notify-send "Getting list of available Wi-Fi networks  " -t 1500
	echo "getting list of wifi networks"

	wifi_list=$(nmcli -t -f IN-USE,SECURITY,SSID,BARS,FREQ device wifi list | awk -F: -v symbol="$connected_symbol" '!seen[$3 $5]++ { selected = ($1 == "*") ? symbol : "   "; if ($2 == "") sec = ""; else if ($2 ~ /WPA/) sec = ""; else if ($2 ~ /WPA2/) sec = ""; else if ($2 ~ /WEP/) sec = ""; else if ($2 ~ /802\\.1X/) sec = ""; else sec = $2; print selected ":" sec ":" $3 ":" $4 ":" $5 }' | sed -E 's/ //g; s/\*\*\*\*/▂▄▆█/g; s/\*\*\* /▂▄▆_/g; s/\*\*  /▂▄__/g; s/\*   /▂___/g; s/    /____/g; s/▂▄▆█/󰤨 /g; s/▂▄▆_/󰤥 /g; s/▂▄__/󰤢 /g; s/▂___/󰤟 /g; s/____/󰤯 /g; s/(2[4-6][0-9]{2}) MHz/ 2.4 GHz/g; s/(5[0-9]{3}) MHz/ 5.0 GHz/g; s/:/ /g')

	wifi_list_menu_height=175
	numbers_of_avail_wifi=$(echo "$wifi_list" | wc -l)
	height_per_wifi_entry=$((wifi_list_menu_height + (numbers_of_avail_wifi * 38)))
	if [[ $height_per_wifi_entry -gt 710 ]]; then
		height_per_wifi_entry=710
	fi

	chosen_network=$(echo -e "$wifi_list\n$goback_wifilist\n$quit" | rofi -x11 -dmenu -i -theme $path_to_theme_search -p " Wifi 󱚻 : " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {location: $location; x-offset: $list_menu_x_offset; y-offset: $list_menu_y_offset; height: ${height_per_wifi_entry}px;}")
	echo $chosen_network
	if [[ $chosen_network == $goback_wifilist ]]; then
		main_menu_wifi
	elif [[ $chosen_network == $quit || $chosen_network == "" ]]; then
		exit 0
	else

		chosen_id=$(echo "$chosen_network" | sed "s///g" | sed "s///g" | sed "s///g" | sed "s///g" | sed "s/󰤨//g" | sed "s/󰤥//g" | sed "s/󰤢//g" | sed "s/󰤟//g" | sed "s/󰤯//g" | sed "s/ 5.0 GHz//g" | sed "s/ 2.4 GHz//g" | sed 's/^[ \t]*//; s/[ \t]*$//')
		chosen_id="$(echo "$chosen_id" | sed "s/$connected_symbol//g")"
		echo $chosen_id
		attempt_message="Attempting to connect to \"$chosen_id\""
		success_message="You are now connected to Wi-Fi network \"$chosen_id\"!"
		saved_connections=$(nmcli -g NAME connection)

		if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
			notify-send "$attempt_message" && nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Connection Established!" "$success_message"
		else
			if [[ "$chosen_network" =~ "" ]]; then
				wifi_password=$(rofi -x11 -dmenu -theme $path_to_theme_set -theme-str "window {height: 8%;}" -password -p "Password  " -theme-str "window {location: $location; x-offset: $list_menu_x_offset; y-offset: $list_menu_y_offset;}")
				case $wifi_password in
				"")
					exit 0
					;;
				esac
				notify-send "$attempt_message" && nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established!" "$success_message"
			elif [[ "$chosen_network" =~ "" ]]; then
				notify-send "$attempt_message" && nmcli device wifi connect "$chosen_id" | grep "successfully" && notify-send "Connection Established!" "$success_message"
			fi
		fi
	fi
}

connect_hidden_network() {
	h_network_ssid=$(rofi -x11 -dmenu -theme $path_to_theme_set -theme-str "window {height: 8%;}" -p "SSID 󰓹 " -theme-str "window {location: $location; x-offset: $list_menu_x_offset; y-offset: $list_menu_y_offset;}")

	if [[ -z $h_network_ssid ]]; then
		notify-send "Network not specified!"
		main_menu_wifi
		return
	fi

	h_network_password=$(rofi -x11 -dmenu -theme $path_to_theme_set -theme-str "window {height: 8%;}" -password -p "Password  " -theme-str "window {location: $location; x-offset: $list_menu_x_offset; y-offset: $list_menu_y_offset;}")

	attempt_message="Attempting to connect to \"$h_network_ssid\""
	success_message="You are now connected to Wi-Fi network \"$h_network_ssid\"!"

	if [[ -z $h_network_password ]]; then
		notify-send "$attempt_message" && nmcli device wifi connect "$h_network_ssid" hidden yes | grep "successfully" && notify-send "Connection Established!" "$success_message"
	else
		notify-send "$attempt_message" && nmcli device wifi connect "$h_network_ssid" password "$h_network_password" hidden yes | grep "successfully" && notify-send "Connection Established!" "$success_message"
	fi
}

main_menu_ethernet() {
	# Detect active or available Ethernet interface name (e.g., eth0, enp3s0)
	eth_dev=$(nmcli -t -f DEVICE,TYPE device | grep ':ethernet' | cut -d: -f1 | head -n1)

	# Fallback in case no specific ethernet device is returned
	if [[ -z "$eth_dev" ]]; then
		eth_dev="eth0"
	fi

	# Check connection status of the interface
	eth_state=$(nmcli -t -f DEVICE,STATE device | grep "^${eth_dev}:" | cut -d: -f2)

	if [[ "$eth_state" == "connected" ]]; then
		toggle="󰈂  Disconnect Ethernet"
	else
		toggle="󰈁  Connect Ethernet"
	fi

	reload_ethernet_connection="󱄋  Reload Ethernet"
	open_gateway_console="󰩩  Access Gateway Interface"
	connection_manager="󰖯  Network Manager"

	select=$(echo -e "$toggle\n$reload_ethernet_connection\n$open_gateway_console\n$connection_manager\n$quit" | rofi -x11 -dmenu -i -p " Ethernet 󰈀  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width_ethernet; height: $main_menu_height_ethernet; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme -mesg "$display_msg")

	# Handle toggle actions
	if [ "$select" = "󰈁  Connect Ethernet" ]; then
		nmcli device connect "$eth_dev"
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Ethernet Connected 󰈁 " -t 850
		main_menu_ethernet
	elif [ "$select" = "󰈂  Disconnect Ethernet" ]; then
		nmcli device disconnect "$eth_dev"
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Ethernet Disconnected 󰈂 " -t 850
		main_menu_ethernet
	fi

	# Handle menu selections
	case $select in
	$reload_ethernet_connection)
		nmcli device disconnect "$eth_dev"
		sleep 0.5
		nmcli device connect "$eth_dev"
		notify-send "Ethernet Reloaded 󱄋 " -t 850
		;;
	$connection_manager)
		nm-connection-editor
		;;
	$open_gateway_console)
		gateway_address=$(ip route show default dev "$eth_dev" 2>/dev/null | awk '{print $3}')
		if [[ -z "$gateway_address" ]]; then
			notify-send "Gateway Address Unavailable"
		else
			xdg-open "http://$gateway_address"
		fi
		;;
	$quit | "")
		exit 0
		;;
	esac
}

both_down() {
	# Detect active or available Ethernet interface name (e.g., eth0, enp3s0)
	eth_dev=$(nmcli -t -f DEVICE,TYPE device | grep ':ethernet' | cut -d: -f1 | head -n1)

	# Fallback in case no specific ethernet device is returned
	if [[ -z "$eth_dev" ]]; then
		eth_dev="eth0"
	fi

	ethernet_opt_enable="󰈁  Connect Ethernet"
	wifi_opt_enable="󱚽  Enable Wi-Fi"

	select=$(echo -e "$wifi_opt_enable\n$ethernet_opt_enable\n$quit" | rofi -x11 -dmenu -i -p " Ethernet 󰈀  " -theme-str "listview {columns: 1; layout: vertical;}" -theme-str "window {width: $main_menu_width_both_down; height: $main_menu_height_both_down; location: $location; x-offset: $main_menu_x_offset; y-offset: $main_menu_y_offset;}" -theme $path_to_theme -mesg "$display_msg")

	case $select in
	"$ethernet_opt_enable")
		nmcli device connect "$eth_dev"
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Ethernet Connected 󰈁 " -t 850
		sleep 0.5
		main_menu_ethernet
		;;
	"$wifi_opt_enable")
		nmcli radio all on
		[[ -n $CUSTOM_SOUND_PATH ]] && paplay $CUSTOM_SOUND_PATH/bell.oga
		notify-send "Wifi Enabled 󱚽 " -t 850
		sleep 0.5
		main_menu_wifi
		;;
	*)
		exit 0
		;;
	esac
}

# main_menu entrypoint
CURRENT_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
INTERFACE_TYPE=$(nmcli device show "$CURRENT_INTERFACE" 2>/dev/null | sed -n 's/GENERAL.TYPE:*//p' | sed 's/[[:space:]]//g')

if [[ $INTERFACE_TYPE == "wifi" ]]; then
	notify-send "Current Interface Is Wifi 󰖩 "
	display_msg="Interface: Wifi 󰖩 "
	main_menu_wifi
elif [[ $INTERFACE_TYPE == "ethernet" ]]; then
	notify-send "Current Interface Is Ethernet  "
	display_msg="Interface: Ethernet  "
	main_menu_ethernet
else
	notify-send "No Used Interface Available 󰛵 "
	display_msg="Interface: N/A 󰛵 "
	both_down
fi
