$mod = SUPER

# Caps Lock
bind = ,Caps_Lock, exec, ~/.config/dunst/scripts/key_notif/capslock_notify.sh

# Num Lock
bind = ,Num_Lock, exec, ~/.config/dunst/scripts/key_notif/numlock_notify.sh

# Audio
binde = ,XF86AudioRaiseVolume, exec, ~/.config/dunst/scripts/volume.sh volume_up
binde = ,XF86AudioLowerVolume, exec, ~/.config/dunst/scripts/volume.sh volume_down
bindl = ,XF86AudioMute, exec, ~/.config/dunst/scripts/volume.sh volume_mute

# Open pavucontrol graphical menu
bind = $mod, XF86AudioMute, exec, pavucontrol
bind = $mod, XF86AudioMicMute, exec, pavucontrol --tab=4

# Microphone
bindl = ,XF86AudioMicMute, exec, ~/.config/dunst/scripts/volume.sh mic_toggle

# Screen Brightness
binde = ,XF86MonBrightnessUp, exec, ~/.config/dunst/scripts/volume.sh brightness_up
binde = ,XF86MonBrightnessDown, exec, ~/.config/dunst/scripts/volume.sh brightness_down

# Airplane mode
bindl = ,XF86RFKill, exec, ~/.config/dunst/scripts/noti-airplane.sh

# Display settings
bindl = ,XF86Display, exec, wdisplays

# Screenshot
bind = ,Print, exec, ~/.config/hypr/scripts/screenshot.sh screen
bind = $mod, Print, exec, ~/.config/hypr/scripts/screenshot.sh window
bind = SHIFT, Print, exec, ~/.config/hypr/scripts/screenshot.sh select

