$mod = SUPER
$alt = ALT

# bind = $mod, t, exec, $TERMINAL
bind = $mod, t, exec, kitty
bind = $mod SHIFT, t, exec, kitty -e tmux

bind = $mod, e, exec, xdg-open .

bind = $mod, g, exec, ~/.config/rofi/scripts/fullscreen-game.sh
bind = $mod, r, exec, ~/.config/rofi/scripts/fullscreen.sh
bind = $alt, r, exec, ~/.config/rofi/scripts/drun.sh
bind = $alt, space, exec, ~/.config/rofi/scripts/drun.sh

bind = $mod, Escape, exec, ~/.config/rofi/modules/rofi-power-menu

bind = $mod, c, exec, xdg-open https://

bind = $mod, m, exec, waypaper

bind = $mod, w, exec, waydroid show-full-ui

bind = $mod, slash, exec, ~/.config/rofi/scripts/emoji_picker.sh
