[charger]
hwp_dynamic_boost = true
governor = performance
energy_performance_preference = performance
turbo = auto
energy_perf_bias = performance

[battery]
hwp_dynamic_boost = false
governor = powersave
energy_performance_preference = power
turbo = never
energy_perf_bias = power
